/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-25 09:56:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header/header.jspf", Long.valueOf(1490422090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- === BEGIN HEADER === -->\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<!--[if IE 8]> <html lang=\"en\" class=\"ie8\"> <![endif]-->\n");
      out.write("<!--[if IE 9]> <html lang=\"en\" class=\"ie9\"> <![endif]-->\n");
      out.write("<!--[if !IE]><!-->\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <!--<![endif]-->\n");
      out.write("    <head>\n");
      out.write("        <!-- Title -->\n");
      out.write("        <title>Boss - Professional Bootstrap Template</title>\n");
      out.write("        <!-- Meta -->\n");
      out.write("        <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("        <meta name=\"description\" content=\"\">\n");
      out.write("        <meta name=\"author\" content=\"\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\n");
      out.write("        <!-- Favicon -->\n");
      out.write("        <link href=\"favicon.ico\" rel=\"shortcut icon\">\n");
      out.write("        <!-- Bootstrap Core CSS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- Template CSS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/animate.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/font-awesome.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/nexus.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/responsive.css\" rel=\"stylesheet\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"assets/css/custom.css\" rel=\"stylesheet\">\n");
      out.write("        <!-- Google Fonts-->\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Raleway:100,300,400\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Roboto:400,300\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       ");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("\t<div name=\"header\" class=\"container\">\r\n");
      out.write("\t\t<nav class=\"navbar navbar-toggleable-md navbar-light bg-faded\">\r\n");
      out.write("\t\t\t<h1>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"main.do\">SEMOCHO</a>\r\n");
      out.write("\t\t\t</h1>\r\n");
      out.write("\t\t\t<div class=\"text-right\">\r\n");
      out.write("\t\t\t\t<form class=\"form-inline my-2 my-lg-0\" style=\"padding-top: 7px;\" method=\"post\" action=\"postTitle.do\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control mr-sm-2\" type=\"text\" name=\"title\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Search\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">Search</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<c:choose>\r\n");
      out.write("\t\t\t\t\t\t<c:when test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser eq null }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"login.jsp\">로그인</a> | <a href=\"join.jsp\">회원 가입</a>\r\n");
      out.write("\t\t\t\t\t\t</c:when>\r\n");
      out.write("\t\t\t\t\t\t<c:otherwise>\r\n");
      out.write("\t\t\t\t\t\t\t<b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>님 !! 환영합니다. [<a href=\"logout.do\">로그아웃</a>] [<a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"alramyList.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">알리미</a>] \r\n");
      out.write("       \t\t\t\t\t\t<a href=\"semoMain.do?id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"fa-home \">홈</a>\r\n");
      out.write("\t\t\t\t\t\t</c:otherwise>\r\n");
      out.write("\t\t\t\t\t</c:choose>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- Header -->\r\n");
      out.write("\t<div id=\"header\" style=\"background-position: 50% 0%; height: 60%;\"\r\n");
      out.write("\t\tdata-stellar-background-ratio=\"0.5\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t<!-- <a href=\"index.html\" title=\"\"> <img\r\n");
      out.write("\t\t\t\t\t\t\tsrc=\"assets/img/%EA%B7%B8%EB%A6%BC1.png\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 400px; height: 228px;\" alt=\"Logo\" />\r\n");
      out.write("\t\t\t\t\t\t</a> -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- End Logo -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- Top Menu -->\r\n");
      out.write("\t\t\t<div id=\"hornav\" class=\"row text-light\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"text-center\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- End Top Menu -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Header -->\r\n");
      out.write("</header>\r\n");
      out.write(" \n");
      out.write("        \n");
      out.write("        <!-- === END HEADER === -->\n");
      out.write("        <!-- === BEGIN CONTENT === -->\n");
      out.write("        <div id=\"content\">\n");
      out.write("            <div class=\"container background-white\">\n");
      out.write("                <div class=\"container\">\n");
      out.write("                    <div class=\"row margin-vert-30\">\n");
      out.write("                        <!-- Login Box -->\n");
      out.write("                        <div class=\"col-md-6 col-md-offset-3 col-sm-offset-3\">\n");
      out.write("                            <form class=\"login-page\" action=\"login.do\" method=\"post\">\n");
      out.write("                                <div class=\"login-header margin-bottom-30\">\n");
      out.write("                                    <h2>Login to your account</h2>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-group margin-bottom-20\">\n");
      out.write("                                    <span class=\"input-group-addon\">\n");
      out.write("                                        <i class=\"fa fa-user\"></i>\n");
      out.write("                                    </span>\n");
      out.write("                                    <input placeholder=\"id\" name=\"id\" class=\"form-control\" type=\"text\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"input-group margin-bottom-20\">\n");
      out.write("                                    <span class=\"input-group-addon\">\n");
      out.write("                                        <i class=\"fa fa-lock\"></i>\n");
      out.write("                                    </span>\n");
      out.write("                                    <input placeholder=\"password\" name = \"password\" class=\"form-control\" type=\"password\">\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-md-6\">\n");
      out.write("                                        <label class=\"checkbox\">\n");
      out.write("                                            <input type=\"checkbox\">Stay signed in</label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-md-6\">\n");
      out.write("                                        <button class=\"btn btn-primary pull-right\" type=\"submit\">Login</button>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                \n");
      out.write("                            </form>\n");
      out.write("                        </div>\n");
      out.write("                        <!-- End Login Box -->\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("<!-- === END FOOTER === -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
