/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-25 10:03:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class postRegister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1489993112000L));
    _jspx_dependants.put("jar:file:/C:/Users/Last%20Pang/Desktop/나무발발이/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/semo/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<head>\r\n");
      out.write("    <!-- Title -->\r\n");
      out.write("    <title>게시물등록</title>\r\n");
      out.write("    <!-- Meta -->\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"favicon.ico\" rel=\"shortcut icon\">\r\n");
      out.write("    <!-- Bootstrap Core CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Template CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/font-awesome.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/nexus.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/responsive.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/custom.css\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- Google Fonts-->\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Raleway:100,300,400\" type=\"text/css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"http://fonts.googleapis.com/css?family=Roboto:400,300\" type=\"text/css\" rel=\"stylesheet\"> </head>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"content\">\r\n");
      out.write("        <div class=\"container background-white\">\r\n");
      out.write("            <div class=\"row margin-vert-30\">\r\n");
      out.write("                <!-- Register Box -->\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3 col-sm-offset-3\">\r\n");
      out.write("                    <form class=\"signup-page margin-top-20\" action=\"postRegister.do\" enctype=\"multipart/form-data\" method=\"post\">\r\n");
      out.write("                        <div class=\"signup-header\">\r\n");
      out.write("                            <h2 class=\"margin-bottom-20\">게시물등록</h2> </div>\r\n");
      out.write("                            \r\n");
      out.write("                        <label>제목</label> <span class=\"color-red\">*</span>\r\n");
      out.write("                        <input class=\"form-control margin-bottom-10\" type=\"text\" name=\"title\">\r\n");
      out.write("                        \r\n");
      out.write("                        <label>카테고리 </label> <span class=\"color-red\">*</span>\r\n");
      out.write("                        <select name=\"category\" class=\"form-control margin-bottom-10\">\r\n");
      out.write("                            <option value=\"\">카테고리 선택</option>\r\n");
      out.write("                            <option value=\"정치와사회\">정치/사회</option>\r\n");
      out.write("                            <option value=\"연예\">연예</option>\r\n");
      out.write("                            <option value=\"스포츠\">스포츠</option>\r\n");
      out.write("                            <option value=\"라이프스타일\">라이프스타일</option>\r\n");
      out.write("                            <option value=\"IT와과학\">IT/과학</option>\r\n");
      out.write("                            <option value=\"문화\">문화</option>\r\n");
      out.write("                            <option value=\"피플\">피플</option>\r\n");
      out.write("                            <option value=\"비즈니스\">비즈니스</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                        \r\n");
      out.write("                        <label>투표 마감일</label> <span class=\"color-red\">*</span>\r\n");
      out.write("                        <input class=\"form-control margin-bottom-10\" type=\"date\" name=\"endDate\">\r\n");
      out.write("                        \r\n");
      out.write("                        <label>선택지 1</label> <span class=\"color-red\">*</span>\r\n");
      out.write("                        <div class=\"panel panel-info\">\r\n");
      out.write("                            <div class=\"panel-heading\">\r\n");
      out.write("                                이미지<input type=\"file\" name=\"leftImage\" id=\"leftImage\"></div>\r\n");
      out.write("                            <div class=\"panel-body\">내용<input type=\"text\" name=\"leftContent\" class=\"form-control margin-bottom-10\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <label>선택지 2</label> <span class=\"color-red\">*</span>\r\n");
      out.write("                        <div class=\"panel panel-info\">\r\n");
      out.write("                            <div class=\"panel-heading\">이미지<input type=\"file\" name=\"rightImage\" id=\"rightImage\"></div>\r\n");
      out.write("                            <div class=\"panel-body\">내용<input type=\"text\" name=\"rightContent\" class=\"form-control margin-bottom-10\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                        <hr size=\"50\">\r\n");
      out.write("                        <div align=\"right\">\r\n");
      out.write("                            <button class=\"btn btn-primary\" type=\"reset\">취소</button>\r\n");
      out.write("                            <button class=\"btn btn-primary\" type=\"submit\">등록</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End Register Box -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
