/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-03-25 09:55:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원 가입</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>jQuery 회원가입</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css\" />\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://code.jquery.com/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://code.jquery.com/ui/1.9.2/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery.ui.datepicker-ko.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\t//$(\"#birth\").datepicker();\r\n");
      out.write("\t\t//$.datepicker.setDefaults( $.datepicker.regional[ \"\" ] );\r\n");
      out.write("\t\t//$(\"#birth\").datepicker($.datepicker.regional[\"ko\"]);\r\n");
      out.write("\t\t$(\"#birth\").datepicker();\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction formCheck() {\r\n");
      out.write("\t\t// submit을 제외한 모든 input태그의 갯수를 가져옴\r\n");
      out.write("\t\tvar length = document.forms[0].length - 1;\r\n");
      out.write("\r\n");
      out.write("\t\tfor (var i = 0; i < length; i++) { // 길이만큼 루프를 돌면서\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (document.forms[0][i].value == null\r\n");
      out.write("\t\t\t\t\t|| document.forms[0][i].value == \"\") {\r\n");
      out.write("\t\t\t\t// 경고창을 띄우고\r\n");
      out.write("\t\t\t\talert(document.forms[0][i].name + \"을(를) 입력하세요.\");\r\n");
      out.write("\t\t\t\t// null인 태그에 포커스를 줌\r\n");
      out.write("\t\t\t\tdocument.forms[0][i].focus();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}//end if\r\n");
      out.write("\t\t}//end for\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#id').keypress(function() {\r\n");
      out.write("\t\t\t$(this).val($(this).val().replace(/^[A-za-z0-9]{10}/g, ''));\r\n");
      out.write("\t\t\t$('font[name=idfont]').html(\"대소문자, 숫자 포함 10자 이내로 입력해주세요.\");\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar st = $(\":input:radio[name=gender]:checked\").val();\r\n");
      out.write("\t\t$('input:radio[name=gender]:input[value=' + st + ']').attr(\"checked\",\r\n");
      out.write("\t\t\t\ttrue);\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$('#tel').keyup(function() {\r\n");
      out.write("\t\t\t$(this).val($(this).val().replace(/[^0-9]/g, \"\"));\r\n");
      out.write("\t\t}); //#tel.keyup \r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#password\").keyup(function() {\r\n");
      out.write("\t\t\t$('font[name=check]').text('');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#passwordCheck\").keyup(function() {\r\n");
      out.write("\t\t\tif ($(\"#password\").val() != $(\"#passwordCheck\").val()) {\r\n");
      out.write("\t\t\t\t$('font[name=check]').text('');\r\n");
      out.write("\t\t\t\t$('font[name=check]').html(\"password가 다릅니다.\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$('font[name=check]').text('');\r\n");
      out.write("\t\t\t\t$('font[name=check]').html(\"password가 동일합니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("<!-- Meta -->\r\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<!-- Bootstrap -->\r\n");
      out.write("<link href=\"form/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<!-- font awesome -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"form/css/font-awesome.min.css\"\r\n");
      out.write("\tmedia=\"screen\" title=\"no title\" charset=\"utf-8\">\r\n");
      out.write("<!-- Custom style -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"form/css/style.css\" media=\"screen\"\r\n");
      out.write("\ttitle=\"no title\" charset=\"utf-8\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<article class=\"container\">\r\n");
      out.write("\t<div class=\"page-header\">\r\n");
      out.write("\t\t<h1>\r\n");
      out.write("\t\t\t회원 가입<small>SEMOCHO</small>\r\n");
      out.write("\t\t</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form name=\"register\" action=\"register.do\" method=\"post\"\r\n");
      out.write("\t\tonsubmit=\"return formCheck();\">\r\n");
      out.write("\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t<col width=\"100\">\r\n");
      out.write("\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t</colgroup>\r\n");
      out.write("\t\t\t<div class=\"col-md-6 col-md-offset-3\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>이름</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"name\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" value=\"\" placeholder=\"이름 입력\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>아이디</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"id\" name=\"id\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"\" placeholder=\"ID 입력\"> <font name=\"idfont\" size=\"2\"\r\n");
      out.write("\t\t\t\t\t\tcolor=\"red\"></font> <span id=\"idCheckResult\"></span></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>비밀 번호</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" id=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"비밀번호 입력\" class=\"form-control\" value=\"\" maxlength=\"\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" id=\"passwordCheck\"\r\n");
      out.write("\t\t\t\t\t\tname=\"passwordCheck\" class=\"form-control\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("\t\t\t\t\t\t<font name=\"check\" size=\"2\" color=\"red\"></font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">성별</td>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"radio\" name=\"gender\" value=\"M\"\r\n");
      out.write("\t\t\t\t\t\tchecked=\"checked\">남 <input type=\"radio\" name=\"gender\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"F\">여</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>생년월일</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"birth\" name=\"birth\" value=\"\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" placeholder=\"생년월일  click\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td id=\"title\">관심사</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"interest\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t<option>society</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>entertainment</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>sports</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>lifeStyle</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>IT</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>culture</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>peole</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option>business</option>\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>이메일</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" id=\"email\" name=\"email\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"form-control\" placeholder=\"이메일 입력\"></td>\r\n");
      out.write("\t\t\t\t\t<td><select id=\"emailDomain\" name=\"emailDomain\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"\" selected>이메일 선택</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"@naver.com\">@naver.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"@nate.com\">@nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"@daum.net\">@daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"@gmail.com\">@gmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>휴대폰 번호</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"tel\" name=\"tel\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"숫자만 입력 가능,-제외\"></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" id=\"grade\" name=\"grade\" value=\"50\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"hidden\" id=\"semo\" name=\"semo\" value=\"50\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<input class=\"btn\" type=\"reset\" value=\"취소\"> <input\r\n");
      out.write("\t\t\t\tclass=\"btn btn-success\" id=\"btn_join\" type=\"submit\" value=\"저장\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</form>\r\n");
      out.write("\t</article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
